export const TODOS_FETCH_REQUESTED = "TODOS_FETCH_REQUESTED";
export const TODOS_FETCH_RECEIVED = "TODOS_FETCH_RECEIVED";
export const TODOS_FETCH_FAILED = "TODOS_FETCH_FAILED";

export const COMPLETE_TODO = "COMPLETE_TODO";